cells = input("Enter cells: ")
print("---------")
print(f"| {cells[0]} {cells[1]} {cells[2]} |")
print(f"| {cells[3]} {cells[4]} {cells[5]} |")
print(f"| {cells[6]} {cells[7]} {cells[8]} |")
print("---------")
